services:
  replicado2mongodb:
    build: .
    image: replicado2mongodb
    container_name: replicado2mongodb
    ports:
      - "8000:80"
    depends_on:
      - mongodb
    networks:
      - replicado2mongodb-network
    volumes:
      - ./:/var/www/html
    environment:
      HOME: /tmp
    user: "${UID:-1000}:${GID:-1000}"

  mongodb:
    image: mongo:7
    container_name: replicado2mongodb_mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: replicado2mongodb
    volumes:
      - mongodb_data:/data/db
    networks:
      - replicado2mongodb-network
  
  mongo-express:
    image: mongo-express:latest
    container_name: replicado2mongodb_mongo_express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:replicado2mongodb@mongodb:27017/admin
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on:
      - mongodb
    networks:
      - replicado2mongodb-network

networks:
  replicado2mongodb-network:

volumes:
  mongodb_data:
